# Generated by Django 4.2.23 on 2025-08-30 08:00

from django.db import migrations, models

import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_options_alter_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photos.models.upload_to_user_directory_with_timestamp),
        ),
    ]
